env:
  contexts:
  - name: baseline
    urls:
    - http://localhost:5001
  parameters:
    failOnError: true
    progressToStdout: false

jobs:
  - type: passiveScan-config
    parameters:
      enableTags: false
      maxAlertsPerRule: 10

  - type: spider
    parameters:
      maxDuration: 1
      url: http://localhost:5001

  - type: passiveScan-wait
    parameters:
      maxDuration: 0

  - type: outputSummary
    parameters:
      format: Long
      summaryFile: /home/zap/zap_out.json

  - type: report
    parameters:
      reportDescription: ''
      reportDir: /zap/wrk/
      reportFile: zap_report.html
      reportTitle: ZAP Scanning Report
      template: traditional-html
