name: CI Pipeline with ZAP Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap_scan:
    name: OWASP ZAP Security Scan
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: Server
        run: npm install

      - name: Start Backend Server
        working-directory: Server
        run: |
          npm start > server.log 2>&1 &
          sleep 15
          curl --retry 5 --retry-delay 5 --fail http://localhost:5001 || (echo "❌ Backend failed to start" && cat server.log && exit 1)

      - name: Run ZAP Automation Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zap.yaml:/zap/wrk/zap.yaml \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun zap.yaml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap_report.html
